"""Add menu item name to order item

Revision ID: 323914b40a37
Revises: 0a8e1a5e34f5
Create Date: 2023-06-15 18:10:06.970883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323914b40a37'
down_revision = '0a8e1a5e34f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('menu_item_name')

    # ### end Alembic commands ###
