"""Remove capacity, description from Table

Revision ID: 637ba91b8b7d
Revises: 74daa7aa268a
Create Date: 2023-06-12 19:05:04.891752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637ba91b8b7d'
down_revision = '74daa7aa268a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
