"""Add order time delivery time

Revision ID: 67b8abdde4ae
Revises: d75dca6ec6cb
Create Date: 2023-06-18 16:12:13.935464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b8abdde4ae'
down_revision = 'd75dca6ec6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('order_time')

    # ### end Alembic commands ###
