"""Add relationship order-table

Revision ID: 74daa7aa268a
Revises: de7c1136214b
Create Date: 2023-06-09 19:15:00.565504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74daa7aa268a'
down_revision = 'de7c1136214b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tables', ['table_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###
