"""empty message

Revision ID: d75dca6ec6cb
Revises: 
Create Date: 2023-06-17 18:31:37.360609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75dca6ec6cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('menu_item_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('menu_item_name')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
